PDFS := $(addsuffix .pdf,$(basename $(shell ls *.tex)))
__FILENAME := ""

tut: ${PDFS}

%.pdf: __FILENAME = $(addsuffix .tex, $(basename $@))
	$(dockerrun)

define dockerrun
	echo Compiling file: ${__FILENAME}
	sltx raw-compile "${__FILENAME}"
endef