name: Compile Slides
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install latexmk
        run: |
          sudo apt-get install latexmk

      - name: Download LaTeX Libraries
        run: |
          mkdir -p ./texinputs/tex/latex
          cd ./texinputs/tex/latex
          git clone https://github.com/EagleoutIce/beamer-themes.git
          git clone https://github.com/EagleoutIce/code-animation.git
          git clone https://github.com/EagleoutIce/color-palettes.git
          git clone https://github.com/EagleoutIce/sopra-collection.git
          export TEXINPUTS=./texinputs//:
      - name: Compile LaTeX document
        run: |
          for texfile in Tut*/*.tex
          do
            latexmk -interaction=nonstopmode -file-line-error -cd -pdf $texfile
          done
      # - name: Upload PDF file
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: PDF
      #     path: ./*.pdf