name: Compile Slides
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2024.4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install git and make
        run: |
          apk add git
          apk add make

      - name: Build LaTeX sources
        run: |
          for texfile in Tut*/*.tex
          do
            latexmk -interaction=nonstopmode -file-line-error -pdf -cd "-emulate-aux-dir" -auxdir=. -outdir=../pdfs -use-make $texfile
            latexmk -C $texfile
          done

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f "pdfs/"
          git commit -m "Compiled slides"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: test-build
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true