name: Compile Slides
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download custom libraries
        run: |
          mkdir -p ./texinputs/tex/latex
          cd ./texinputs/tex/latex
          git clone https://github.com/EagleoutIce/beamer-themes.git
          git clone https://github.com/EagleoutIce/code-animation.git
          git clone https://github.com/EagleoutIce/color-palettes.git
          git clone https://github.com/EagleoutIce/sopra-collection.git
          export TEXINPUTS=./texinputs//:

      - name: Setup docker/Prepare
        run: docker build --pull --tag 'mydocker' --file '.github/workflows/Dockerfile' .
      
      - name: Run docker/Compile
        run: docker run mydocker:latest