name: Compile Slides
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2024.4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download custom libraries
        run: |
          apk add git
          mkdir -p ./texinputs/tex/latex
          cd ./texinputs/tex/latex
          git clone https://github.com/EagleoutIce/beamer-themes.git
          git clone https://github.com/EagleoutIce/code-animation.git
          git clone https://github.com/EagleoutIce/color-palettes.git
          git clone https://github.com/EagleoutIce/sopra-collection.git

      - name: Build LaTeX sources
        run: |
          for texfile in Tut*/*.tex
          do
            latexmk -interaction=nonstopmode -file-line-error -pdf -cd "-emulate-aux-dir" -auxdir=. -outdir=../pdfs -e "ensure_path('TEXINPUTS','./texinputs//:')" $texfile
            latexmk -C $texfile
          done

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f "pdfs/"
          git commit -m "Compiled slides"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: test-build
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true