name: Compile Slides
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2024.4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download custom libraries
        run: |
          apk add git
          mkdir -p ./texinputs/tex/latex
          cd ./texinputs/tex/latex
          git clone https://github.com/EagleoutIce/beamer-themes.git
          git clone https://github.com/EagleoutIce/code-animation.git
          git clone https://github.com/EagleoutIce/color-palettes.git
          git clone https://github.com/EagleoutIce/sopra-collection.git

      - name: Compile PDFs # texinputs is in .. -.-
        run: |
          for texfile in Tut*/*.tex
          do
            mv $texfile ${texfile/.tex/_anim.tex}
            animfile=${texfile#*/}
            echo "\\PassOptionsToClass{handout}{beamer}\\input{${animfile/.tex/_anim.tex}}" > $texfile;
            latexmk -interaction=nonstopmode -file-line-error -pdf -cd "-emulate-aux-dir" -auxdir=. -outdir=../pdfs -e "ensure_path('TEXINPUTS','../texinputs//:')" $texfile
            latexmk -C $texfile
            latexmk -interaction=nonstopmode -file-line-error -pdf -cd "-emulate-aux-dir" -auxdir=. -outdir=../pdfs -e "ensure_path('TEXINPUTS','../texinputs//:')" ${texfile/.tex/_anim.tex}
            latexmk -C ${texfile/.tex/_anim.tex}
          done

      - name: Push slides to builds
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source_file: 'pdfs'
          destination_repo: 'Laqco/wwu-info1-ws24'
          destination_branch: builds
          user_email: 'action@github.com'
          user_name: 'GitHub Action'
          commit_message: 'Compiled slides'