name: Compile Slides
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2024.4-minimal
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download custom libraries
        run: |
          mkdir -p ./texinputs/tex/latex
          cd ./texinputs/tex/latex
          apk add git
          git clone https://github.com/EagleoutIce/beamer-themes.git
          git clone https://github.com/EagleoutIce/code-animation.git
          git clone https://github.com/EagleoutIce/color-palettes.git
          git clone https://github.com/EagleoutIce/sopra-collection.git
          export TEXINPUTS=./texinputs//:
      
      - name: Install texliveonfly
        run: |
          apk add --update --no-cache python3
          ln -sf python3 /usr/bin/python
          python3 -m ensurepip
          pip3 install sltx

      - name: Build using latexmk
        run: |
          for dir in Tut*
          do
            cd $dir
            for texfile in *.tex
            do
              sltx raw-compile $texfile
            done
            cd ..
          done

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f "pdfs/"
          git commit -m "Compiled slides"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: test-build
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true